// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHtC38Hsw1D4PQue0wI_EeVLL9RO4Njq0',
    appId: '1:688733753327:web:67ed7ecda5a21c1526f01a',
    messagingSenderId: '688733753327',
    projectId: 'workshop-management-syst-b9cec',
    authDomain: 'workshop-management-syst-b9cec.firebaseapp.com',
    storageBucket: 'workshop-management-syst-b9cec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBujwEYe1M63CZsBmhBACtykfRJVMhUoxw',
    appId: '1:688733753327:android:2e800c36e1d4ed1d26f01a',
    messagingSenderId: '688733753327',
    projectId: 'workshop-management-syst-b9cec',
    storageBucket: 'workshop-management-syst-b9cec.firebasestorage.app',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBB0LmbWiJsEjp1Kq5A1OK_mmZ1icdzZaE',
  //   appId: '1:688733753327:android:2e800c36e1d4ed1d26f01a',
  //   messagingSenderId: '797068714189',
  //   projectId: 'workshop-management-syst-b9cec',
  //   storageBucket: 'workshop-management-syst-b9cec.firebasestorage.app',
  //   androidClientId: '797068714189-3vb8vq0hhroi0gkjc0r50epua4rvsk7k.apps.googleusercontent.com',
  //   iosClientId: '797068714189-krui6e6o4u6cbtp2iiel60svdmjmk0ij.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.diabetesRiskPredictionAndHealthManagementSystem',
  // );
  //
  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyBB0LmbWiJsEjp1Kq5A1OK_mmZ1icdzZaE',
  //   appId: '1:688733753327:android:2e800c36e1d4ed1d26f01a',
  //   messagingSenderId: '797068714189',
  //   projectId: 'workshop-management-syst-b9cec',
  //   storageBucket: 'workshop-management-syst-b9cec.firebasestorage.app',
  //   androidClientId: '797068714189-3vb8vq0hhroi0gkjc0r50epua4rvsk7k.apps.googleusercontent.com',
  //   iosClientId: '797068714189-krui6e6o4u6cbtp2iiel60svdmjmk0ij.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.diabetesRiskPredictionAndHealthManagementSystem',
  // );
  //
  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyAalYUvHbJBAaL7YyjdYhHwtt63FYOtqjI',
  //   appId: '1:688733753327:android:2e800c36e1d4ed1d26f01a',
  //   messagingSenderId: '797068714189',
  //   projectId: 'workshop-management-syst-b9cec',
  //   authDomain: 'diabetes-health-system.firebaseapp.com',
  //   storageBucket: 'workshop-management-syst-b9cec.firebasestorage.app',
  //   measurementId: 'G-112Y2V104J',
  // );
}
